version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-tooling:
        dependency-type: development
        patterns:
          - mypy
          - pytest
          - pytest-cov
          - ruff

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
